# Generated by Django 3.1.1 on 2022-12-19 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('privacy', models.CharField(choices=[('pub', 'public'), ('fr', 'friends')], max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupRequestJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouprequestjoingroup', to='groups.group')),
                ('requestFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouprequestjoinfrom', to=settings.AUTH_USER_MODEL)),
                ('requestTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouprequestjointo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupinvitegroup', to='groups.group')),
                ('inviteFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupinvitefrom', to=settings.AUTH_USER_MODEL)),
                ('inviteTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupinviteto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
